# Binance API'leri ve Akışları için Resmi Belgeler. 
* API ve Akışlar ile ilgili değişiklikler, kesintiler vb. ile ilgili Resmi Duyurular burada bildirilecektir: **https://t.me/binance_api_announcements** 
* Bu havuzdaki belgelerde açıklanan Akışlar, uç noktalar, parametreler, yükler vb. **resmi** ve **desteklenen** olarak kabul edilir. 
* Başka herhangi bir Akış, uç nokta, parametre veya yükün vb. kullanımı **desteklenmez**; **bunları kendi riskinizle ve hiçbir garanti olmaksızın kullanın.** 


Ad | Açıklama 
------------ | ------------ 
[Api.txt](https://github.com/user-attachments/files/16853493/Api.txt) 
[README (2).md](https://github.com/user-attachments/files/16853492/README.2.md) 

[enums.md](./enums.md) | REST ve WebSocket API tarafından kullanılan enum'lar hakkında ayrıntılar 
[errors.md](./errors.md) | Spot API'sinin hata kodları ve mesajları 
[filters.md](./filters.md) | Spot API tarafından kullanılan filtreler hakkında ayrıntılar 
[rest-api.md](./rest-api.md) | Spot REST API (`/api`) 
[web-socket-api.md](./web-socket-api.md) | Spot WebSocket API 
[web-socket-streams.md](./web-socket-streams.md) | Spot Piyasa Verileri WebSocket akışları 
[user-data-stream.md](./user-data-stream.md) | Spot Kullanıcı Verileri WebSocket akışları 
[sbe_schemas](./sbe/schemas/) | Spot Basit İkili Kodlama (SBE) şemaları 
[testnet](./testnet/) | Yalnızca SPOT Testnet'te bulunan özellikler için API belgeleri 
| 
[Marj Ticareti](https://developers.binance.com/docs/margin_trading) | Marj Ticareti Hakkında Ayrıntılar 
[Türev UM Vadeli İşlemleri](https://developers.binance.com/docs/derivatives/usds-margined-futures/general-info) | Türev UM Vadeli İşlemleri (`/fapi`) Hakkında Ayrıntılar 
[Türev CM Vadeli İşlemleri](https://developers.binance.com/docs/derivatives/coin-margined-futures/general-info) | Türev CM Vadeli İşlemleri (`/dapi`) Hakkında Ayrıntılar 
[Türev Opsiyonlar](https://developers.binance.com/docs/derivatives/option/general-info) | Türev Avrupa Opsiyonları (`/eapi`) Hakkında Ayrıntılar 
[Türev Portföy Marjı](https://developers.binance.com/docs/derivatives/portfolio-margin/general-info)| Türev Portföy Marjı (`/papi`) Hakkında Ayrıntılar 
[Cüzdan](https://developers.binance.com/docs/wallet) | Cüzdan uç noktaları hakkında ayrıntılar (`/sapi`) 
[Alt Hesap](https://developers.binance.com/docs/sub_account/general-info) | Alt Hesap istekleri hakkında ayrıntılar (`/sapi`) 
[Basit Kazanç](https://developers.binance.com/docs/simple_earn/general-info) | Basit Kazanç hakkında ayrıntılar 
[Çift Yatırım](https://developers.binance.com/docs/dual_investment) | Çift Yatırım hakkında ayrıntılar 
[Otomatik Yatırım](https://developers.binance.com/docs/auto_invest) | Otomatik Yatırım hakkında ayrıntılar
[Stake](https://developers.binance.com/docs/staking) | Staking Hakkında Ayrıntılar 
[Madencilik](https://developers.binance.com/docs/mining) | Madencilik Hakkında Ayrıntılar 
[Algoritmik Ticaret](https://developers.binance.com/docs/algo) | Algoritmik Ticaret Hakkında Ayrıntılar 
[Kopyalama Ticareti](https://developers.binance.com/docs/copy_trading) | Kopyalama Ticareti Hakkında Ayrıntılar 
[Porfolio Margin Pro](https://developers.binance.com/docs/derivatives/portfolio-margin-pro/general-info) | Portfolio Margin Pro Hakkında Ayrıntılar 
[Fiat](https://developers.binance.com/docs/fiat) | Fiat Hakkında Ayrıntılar| 
[C2C](https://developers.binance.com/docs/c2c) |C2C hakkında ayrıntılar| 
[VIP Kredi](https://developers.binance.com/docs/vip_loan) |VIP Kredisi Hakkında Ayrıntılar 
[Kripto Kredisi](https://developers.binance.com/docs/crypto_loan) |Kripto Kredisi Hakkında Ayrıntılar 
[Ödeme](https://developers.binance.com/docs/binance-pay) |Binance Pay Hakkında Ayrıntılar 
[Dönüştür](https://developers.binance.com/docs/convert) |Dönüştür API'si Hakkında Ayrıntılar 
[İade](https://developers.binance.com/docs/rebate) |Spot İadesi Hakkında Ayrıntılar 
[NFT](https://developers.binance.com/docs/nft) |NFT istekleri Hakkında Ayrıntılar 
[Hediye Kartı](https://developers.binance.com/docs/gift_card) | Hediye Kartı API'si Hakkında Ayrıntılar 

# SSS 


Adı | Açıklama 
------------- | ------------ 
[spot_glossary](./faqs/spot_glossary.md) | API'de kullanılan terimlerin tanımları 
[commissions_faq](./faqs/commissions_faq.md) | API'de komisyon hesaplamalarının açıklanması 
[trailing-stop-faq](./faqs/trailing-stop-faq.md) | API'de Trailing Stop'ların davranışı hakkında ayrıntılı bilgi 
[stp_faq](./faqs/stp_faq.md) | API'de Self Trade Prevention (diğer adıyla STP) davranışı hakkında ayrıntılı bilgi 
[market-data-only](./faqs/market_data_only.md) | Yalnızca piyasa verisi API'miz ve websocket akışlarımız hakkında bilgi. 
[sor_faq](./faqs/sor_faq.md) | Akıllı Sipariş Yönlendirme (SOR) 
[order_count_decrement](./faqs/order_count_decrement.md) | Spot Sipariş Sayım Sınırı Kurallarında Güncellemeler. 
[sbe_faq](./faqs/sbe_faq.md) | API'de Basit İkili Kodlamanın (SBE) uygulanmasına ilişkin bilgiler 

# Değişiklik günlüğü 

API'lerimiz ve Akış Sağlayıcılarımızdaki en son değişiklikler için lütfen [CHANGELOG](./CHANGELOG.md) adresine bakın. 
```HTML 
# Nodejs'deki Binance bağlayıcısı 

[![npm sürümü](https://badge.fury.io/js/%40binance%2Fconnector.svg)](https://badge.fury.io/js/%40binance%2Fconnector) 
[![Düğüm sürümü](https://img.shields.io/node/v/%40binance%2Fconnector.svg?style=flat)](http://nodejs.org/download/) 
[![Standard-Js](https://img.shields.io/badge/code_style-standard-brightgreen.svg)](https://standardjs.com/)
[![Lisans: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT) 


Bu, [Api.txt](https://github.com/user-attachments/files/16853358/Api.txt) için bir bağlayıcı olarak çalışan hafif bir kütüphanedir 
. Minimum bağımlılıklarla basit, temiz ve kullanımı kolay olacak şekilde tasarlanmıştır. 

- Desteklenen API'ler: 
    - `/api/*` 
    - `/sapi/*` 
    - Spot Websocket Market Stream 
    - Spot Kullanıcı Veri Akışı 
    - Spot Websocket API'si 
- Test vakaları ve örneklerin eklenmesi 
- Özelleştirilebilir temel URL 
- Destek isteği zaman aşımı ve HTTP proxy'si (v2'den beri) 
- Yanıt meta verileri görüntülenebilir 
- Özelleştirilebilir Kaydedici 


## Kurulum 

```bash 
npm install @binance/connector 
``` 

## Belgeler 

[https://binance.github.io/binance-connector-node/](https://binance.github.io/binance-connector-node/) 

## RESTful API'leri 



```javascript 
const { Spot } = require('@binance/connector') 

const apiKey = '[Api.txt](https://github.com/user-attachments/files/16853377/Api.txt) 
' 
const apiSecret = '' 
const client = new Spot(apiKey, apiSecret) 

// Hesap bilgilerini al 
client.account().then(response => client.logger.log(response.data)) 

// Yeni bir sipariş ver 
client.newOrder('BNBUSDT', 'BUY', 'LIMIT', { 
  price: '350', 
  amount: 1, 
  timeInForce: 'GTC' 
}).then(response => client.logger.log(response.data)) 
  .catch(error => client.logger.error(error)) 

``` 

Daha fazla uç noktayı kontrol etmek için lütfen `examples` klasörünü bulun. 

## Anahtar Çifti Tabanlı Kimlik Doğrulama 

```javascript 
const { Spot, PrivateKeyAlgo } = [Api.txt](https://github.com/user-attachments/files/16853382/Api.txt) 
require('@binance/connector') 

const apiKey = '' 
const apiSecret = '' // RSA özel anahtarı sağlandığında hiçbir etkisi yoktur 

// özel anahtarı yükle 
const privateKey = fs.readFileSync('/Users/john/ssl/private_key_encrypted.pem') 
const privateKeyPassphrase = 'password' 
const privateKeyAlgo = PrivateKeyAlgo.RSA // RSA anahtarı için 
const privateKeyAlgo = PrivateKeyAlgo.ED25519 // Ed25519 anahtarı için 

const client = new Spot(apiKey, apiSecret, { 
  privateKey, 
  privateKeyPassphrase, // yalnızca şifrelenmiş anahtar 
  privateKeyAlgo için kullanılır 
}) 

// Hesap bilgilerini al 
client.account().then(response => client.logger.log(response.data)) 
``` 

### Testnet

`/sapi/*` uç noktaları henüz testnet ortamına sahip olmasa da, `/api/*` uç noktaları 
[Spot Testnet](https://testnet.binance.vision/)'da test edilebilir. Bunu temel URL'yi değiştirerek kullanabilirsiniz: 

```javascript 
// testnet temel URL'sini sağlayın 
const client = new Spot(apiKey, apiSecret, { baseURL: 'https://testnet.binance.vision'}) 
``` 

### Temel URL 

`base_url` sağlanmazsa, varsayılan olarak `api.binance.com` olur. 

Üretim aşamasında bile `base_url` parametresinin geçirilmesi önerilir; zira Binance, performans sorunları durumunda alternatif URL'ler sağlar: 

- `https://api1.binance.com` 
- `https://api2.binance.com` 
- `https://api3.binance.com` 

### İsteğe Bağlı Parametreler 

İsteğe bağlı parametreler, son fonksiyon parametresi olarak tek bir nesneye kapsüllenir. 

```javascript 
const { Spot } = require('@binance/connector') 

const apiKey = 'c9f3tCe0l34EUaaPSiL9s0KtyRC4mDG0rK4KRPTdxiqhjrCrbgZeTibcexLLApP0' 
const apiSecret = 'Cittld17y7ynFYzy7NeexmVy0uzLV23OOS1JHFKfz95X1aLFP7Vv75gmCSqmGqL5' 
const client = new Spot(apiKey, apiSecret) 

client.account({ recvWindow: 2000 }).then(response => client.logger.log(response.data)) 

``` 


``` 
# Faydalı Kaynaklar 

* [Postman Koleksiyonlar](https://github.com/binance/binance-api-postman) 
    * Postman koleksiyonları mevcuttur ve API ile hızlı ve kolay bir başlangıç ​​arayan yeni kullanıcılara önerilir. 
* Bağlayıcılar 
    * Aşağıdakiler, farklı dillerde yazılmış, Binance genel API'sine bağlayıcı olarak çalışan hafif kütüphanelerdir: 
        * [Python](https://github.com/binance/binance-connector-python) 
        * [Node.js](https://github.com/binance/binance-connector-node) 
        * [Ruby](https://github.com/binance/binance-connector-ruby) 
        * [DotNET C#](https://github.com/binance/binance-connector-dotnet) 
        * [Java](https://github.com/binance/binance-connector-java) 
        * [Rust](https://github.com/binance/binance-spot-connector-rust) 
        * [PHP](https://github.com/binance/binance-connector-php) 
        * [Go](https://github.com/binance/binance-connector-go) 
        * [TypeScript](https://github.com/binance/binance-connector-typescript) 
* [Swagger](https://github.com/binance/binance-api-swagger) 
    * RESTful API için OpenAPI spesifikasyonuna sahip bir YAML dosyası ve referans için bir Swagger kullanıcı arayüzü sayfası mevcuttur. 
* [Spot Testnet](https://testnet.binance.vision/) 
    * Kullanıcılar SPOT ticareti yapmak için SPOT Testnet'i kullanabilirler. 
    * Şu anda bu yalnızca API aracılığıyla kullanılabilir.
    * Sadece `/api/*` ile başlayan uç noktalar desteklenir, `/sapi/*` desteklenmez. 

# Bizimle İletişime Geçin 

* [Binance API Telegram Grubu](https://t.me/binance_api_english) 
    * API ve/veya Websocket'lerle ilgili ani performans düşüşleriyle ilgili sorularınız için. 
    * Dokümanlarda yer almayan API ile ilgili genel sorularınız için. 
* [Binance Geliştiricileri](https://dev.binance.vision/) 
    * API ve/veya Websocket'lerle kod uygulamasıyla ilgili sorularınız/yardımlarınız için. 
* [Binance Müşteri Desteği](https://www.binance.com/en/support-center) 
    * Eksik fonlar, 2FA ile ilgili yardım vb. durumlar için.
